name: kafka-consumer
port: &port 3000
replicaCount: 2
image: osskit/dafka-consumer:1.0.0
usePrometheus: true

secret:
  provider:
  resourceName:
  fileName:

auth:
  saslUsername:
  saslPasswordFilePath: /secrets-files/SASL_PASSWORD  

target:
  protocol: http
  baseUrl:
  port: 80
  isAlive: /isAlive

livenessProbe:
  httpGet:
    path: /isAlive
    port: *port
readinessProbe:
  httpGet:
    path: /isAlive
    port: *port

resources:
  requests:
    cpu: '400m'
    memory: '400Mi'
  limits:
    cpu: '800m'
    memory: '800Mi'

metrics:
  enabled: true
  path: /metrics 
